language: node_js
node_js:
  - "7"
sudo: required
services:
  - docker

before_install:
  - docker build -t hsz4docker/react-test -f ./client/Dockerfile.dev ./client
  # add dev build for more test, i.e server and worker.

script:
  - docker run hsz4docker/react-test npm test -- --coverage
  # add dev build for more test, i.e server and worker.

after_success:
  - docker build -t hsz4docker/multi-client ./client
  - docker build -t hsz4docker/multi-nginx ./nginx
  - docker build -t hsz4docker/multi-server ./server
  - docker build -t hsz4docker/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push images to dockerhub
  - docker push hsz4docker/multi-client
  - docker push hsz4docker/multi-nginx
  - docker push hsz4docker/multi-server
  - docker push hsz4docker/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: eu-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-eu-west-1-xxxxx
#   buicket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY



